---

- name: Include vars
  hosts: head
  tasks:
    - include_vars: vars/cord-pod_defaults.yml
    - include_vars: vars/cord-stack_defaults.yml

- name: Prerequisites
  hosts: head
  sudo: yes
  roles:
    - prereqs

- name: Local Environment
  hosts: head
  roles:
    - local_environment

- name: Download images
  hosts: head
  roles:
    - download_images

- name: Build Config
  hosts: head
  roles:
    - buildconfig

- name: Bootstrap
  hosts: head
  roles:
    - bootstrap

- name: Onboarding
  hosts: head
  roles:
    - onboarding

- name: Configuration
  hosts: head
  roles:
    - config
  tags:
    - config

